@startuml
title 基于GitHub的实验管理平台--修改用户信息用例的顺序图
actor user
actor 前端页面
actor 服务器
database 后台数据
user -> 前端页面:点击修改用户信息
前端页面 -> 前端页面:从session中获取用户信息，并在修改界面中显示
user -> 前端页面:输入修改内容
前端页面 -> 前端页面:验证输入的合法性
前端页面 -> 服务器:发送更新用户信息请求
服务器 -> 服务器:获取用户信息
服务器 -> 后台数据:保存用户信息
后台数据 -> 前端页面:返回经过修改的用户信息
@enduml