@startuml
title 基于GitHub的实验管理平台--修改用户密码用例的顺序图
actor user
actor 前端页面
actor 服务器
database 后台数据
user -> 前端页面:输入新旧密码信息
前端页面 -> 前端页面:验证输入的合法性
前端页面 -> 前端页面:验证新旧两次密码是否一致
前端页面 -> 服务器:传入加密过的用户id以及旧密码
服务器 -> 服务器:解读获取到的经过加密的用户id以及旧密码
服务器 -> 后台数据:根据用户id查找在数据库中存储的加密密码
后台数据 -> 服务器:返回加密密码
服务器 -> 服务器:严重旧密码是否正确
服务器 -> 前端页面:返回成功
前端页面 -> 前端页面:确认修改密码
前端页面 -> 服务器:传入用户id以及新的密码
服务器 -> 后台数据:传入新的密码

@enduml