@startuml
title 基于GitHub的实验管理平台--查看用户信息用例的顺序图
actor user
actor 前端页面
actor 服务器
database 后台数据
user -> 前端页面:点击查看用户信息
前端页面 -> 前端页面:松session取出经过私钥加密的用户信息，并用公钥解读获得用户信息
前端页面 -> 服务器:发送获取更多用户请求，并使用id传入
服务器 -> 服务器:获取用户id，及用户类型
服务器 -> 后台数据:根据用户类型及id获取其基本用户信息
后台数据 -> 前端页面:返回获取到的用户信息
前端页面 -> 前端页面:显示得到的用户信息
@enduml